services:
  - docker

env:
  - SPARROW_DB_PORT=5433 SPARROW_HTTP_PORT=80 SPARROW_SECRET_KEY="TemporaryKey" SPARROW_SITE_CONTENT="$(pwd)/import-pipelines/WiscAr/site-content" SPARROW_BACKUP_DIR="$(pwd)/path_to_whatever/backups" pipeline=$(pwd)/Sparrow/import-pipelines/LaserChron SPARROW_INIT_SQL="$pipeline/sql" SPARROW_COMMANDS="$pipeline/bin" SPARROW_BASE_URL="/" 

before_script:
  - docker-compose up --build -d

script:
  - ./test.sh

after_script:
  - docker-compose down
