version: "3.4"
services:
  gateway:
    depends_on:
      - backend
      - frontend
    ports:
      - ${SPARROW_HTTP_PORT:-5002}:80
    volumes:
      - ./nginx-config/locations:/etc/nginx/locations:ro
      - frontend_build:/frontend
      - ${SPARROW_DATA_DIR:-placeholder}:/data:ro
  backend:
    build:
      context: backend
      target: main
    command: /bin/run
    # Make sure we get colorized terminal output
    tty: true
    expose:
      - 5000
    depends_on:
      - db
    environment:
      - SPARROW_SECRET_KEY
      - SPARROW_BASE_URL
      - SPARROW_LAB_NAME
      - SPARROW_INIT_SQL=/init-sql
      # For cloud data support
      # NOTE: it may be useful to split this into a
      # separate container, but it's centralized
      # for now...
      - SPARROW_S3_ENDPOINT
      - SPARROW_S3_BUCKET
      - SPARROW_S3_KEY
      - SPARROW_S3_SECRET
    volumes:
      # Volume for scripts to make things like
      # migrations work...
      # TODO: come up with a better way to organize
      - ./bin:/sparrow-bin
      # Read-only volume for source code
      - ./backend/:/app
      # Nested volume to keep built files
      # separate from those on our local system
      - /app/sparrow.egg-info
      # Share some configuration between backend
      # and frontend
      - ${SPARROW_INIT_SQL:-placeholder}:/init-sql/:ro
      # The docker-compose volume for sparrow commands needs to be set
      # even if a `SPARROW_COMMANDS` directory is not provided, so we can
      # use a placeholder.
      - ${SPARROW_COMMANDS_VOLUME:-placeholder}:/sparrow-commands/:ro
      # Link `SPARROW_PLUGIN_DIR` directly into site-packages as a folder
      # ...we could probably do this in a more elegant way
      - ${SPARROW_PLUGIN_DIR:-placeholder}:/usr/local/lib/python3.8/site-packages/sparrow_plugins:ro
      # Save ipython configuration to anonymous volume so
      # we keep command history between app runs
      - ipython_config:/root/.ipython/profile_default
  db:
    image: mdillon/postgis:11
    expose:
      - 5432
    ports:
      # A port range can be specified, but only with recent versions of Docker,
      # so we default to a single port.
      - ${SPARROW_DB_PORT:-54321}:5432
    environment:
      - POSTGRES_DB=sparrow
    volumes:
      - db_cluster:/var/lib/postgresql/data
  frontend:
    build: frontend
    depends_on:
      - backend
    environment:
      - CONTAINERIZED=1
      - SPARROW_LAB_NAME
      - SPARROW_BASE_URL
      - MAPBOX_API_TOKEN
      # SPARROW_SITE_CONTENT variable is different
      # inside and outside of the container
      - SPARROW_SITE_CONTENT=/app/site-content
      - SPARROW_ENV
    volumes:
      - ./frontend/src:/app/src
      - frontend_build:/app/_assets
      # Right now, we configure default site content
      # rather than allowing any customization
      - ${SPARROW_SITE_CONTENT:-./frontend/default-content}:/app/site-content
  api-tests:
    build: api-tests
    # A placeholder command
    command: echo
    depends_on:
      - backend
volumes:
  frontend_build:
  # Anonymous volume to preserve `sparrow shell` history
  ipython_config:
  db_cluster:
  # Placeholder volumes in case we don't have these volumes to mount
  placeholder:
