# Modifies containers for dev hot reloading
version: "3.6"
services:
  frontend:
    build:
      context: frontend
      target: base
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
volumes:
  frontend_node_modules: