version: "3.4"
services:
  gateway:
    image: nginx:1.15
    depends_on:
      - backend
      - frontend
    ports:
      - $SPARROW_HTTP_PORT:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/frontend
      - $SPARROW_DATA_DIR:/data:ro
  backend:
    build: backend
    expose:
      - 5000
    depends_on:
      - db
    environment:
      - SPARROW_SECRET_KEY
      - SPARROW_BASE_URL
      - SPARROW_LAB_NAME
      - SPARROW_INIT_SQL=/init-sql
    volumes:
      # Volume for scripts to make things like
      # migrations work...
      # TODO: come up with a better way to organize
      - ./bin:/sparrow-bin
      # Read-only volume for source code
      - ./backend/:/app
      # Nested volume to keep built files
      # separate from those on our local system
      - /app/sparrow.egg-info
      # Share some configuration between backend
      # and frontend
      - $SPARROW_INIT_SQL:/init-sql/
      - $SPARROW_COMMANDS_VOLUME:/sparrow-commands/
  db:
    image: mdillon/postgis:11
    expose:
      - 5432
    ports:
      - $SPARROW_DB_PORT:5432
    environment:
      - POSTGRES_DB=sparrow
    volumes:
      - db_cluster:/var/lib/postgresql/data
  frontend:
    build: frontend
    depends_on:
      - backend
    environment:
      - CONTAINERIZED=1
      - SPARROW_LAB_NAME
      - SPARROW_BASE_URL
      - MAPBOX_API_TOKEN
      # SPARROW_SITE_CONTENT variable is different
      # inside and outside of the container
      - SPARROW_SITE_CONTENT=/app/site-content
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend_build:/app/_assets
      # Right now, we configure default site content
      # rather than allowing any customization
      - $SPARROW_SITE_CONTENT:/app/site-content
volumes:
  frontend_build:
  db_cluster:
  # Placeholder volumes in case we don't have these volumes to mount
  placeholder:
