version: "3.6"
services:
  # Set restart policy to allow docker
  # to bring these containers back up on system
  # reboot.
  gateway:
    restart: unless-stopped
  backend:
    restart: unless-stopped
  db:
    restart: unless-stopped
