version: "3.4"
services:
  frontend:
    build:
      context: ..
      dockerfile: docs/Dockerfile
      # We build to docs-base for development, to allow for auto-reloading
      target: docs-base
    command: node_modules/.bin/docusaurus start --host 0.0.0.0 --port 3000
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/docs
      #- /docs/.cache
      - node_modules:/docs/node_modules
      - cache:/docs/.docusaurus
volumes:
  cache:
  node_modules:
