version: "3.4"
services:
  frontend:
    build:
      context: ..
      dockerfile: docs/Dockerfile
    expose:
      - 8000
    ports:
      - "3000:3000"
    volumes:
      - .:/docs
      - /docs/.cache
      - /docs/node_modules
      - public:/docs/public
volumes:
  public:
  #node_modules:
