version: "3.4"
services:
  main:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - public:/app/public
  main1:
    image: nginxdemos/hello
    ports:
      - "3001:80"
volumes:
  public:
  #node_modules:
