name: Sparrow tests
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Install CLI build dependencies
      run: sudo apt-get update && sudo apt-get -y install python3 python3-venv
    - name: Build command-line application
      run: _cli/_scripts/build-local
    - name: Run Sparrow core tests
      env:
        SPARROW_SECRET_KEY: test
      run: source _cli/build/venv/bin/activate && bin/sparrow test
