name: Sparrow continuous integration
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Install CLI build dependencies
        run: sudo apt-get update \
          sudo apt-get -y install python3 python3-venv

      # Bundling
      - name: Bundle command-line application with PyInstaller
        run: make \
          sudo make install-dev

      - name: Run Sparrow tests for built application
        run: sparrow test

