name: Sparrow tests
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install CLI build dependencies
      run: sudo apt-get update && sudo apt-get -y install python3 python3-venv
    - name: Build command-line application
      run: make install-dev
    - name: Run Sparrow core tests
      run: sparrow test
