name: Documentaton website continuous integration
on:
  push:
    branches: [ master, docs ]
  pull_request:
    branches: [ master, docs ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PKG_ROOT: docker.pkg.github.com/earthcubegeochron/sparrow/
    steps:
    # https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei
    - uses: actions/checkout@v2
    - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
    - name: Build Docker images
      run: docs/.ci/1-build-images
    - name: Test that website loads properly
      run: docs/.ci/2-run-tests
    - name: Push new images to GitHub Packages
      run: docs/.ci/3-push-images
    # Deployment:
    # Passes a webhook to the specified URL used for deployment
    # A webhook receiver such as https://github.com/staticfloat/docker-webhook
    # should be integrated into the destination
    - name: Send webhook to kick off deployment
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_url: ${{ secrets.DOCUMENTATION_DEPLOYMENT_ENDPOINT }}
        webhook_secret: ${{ secrets.DOCUMENTATION_DEPLOYMENT_SECRET }}
