name: Documentaton website continuous integration
on:
  push:
    branches: [ master, docs ]
  pull_request:
    branches: [ master, docs ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test that documentation website builds properly
      run: docs/test-docs
    - name: Deploy the application
      run: echo
