name: Format code
on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: rickstaa/action-black@v1
        with:
          black_args: "backend/**/*.py _cli/**/*.py"
      - uses: actionsx/prettier@v2
        with:
          # prettier CLI arguments.
          args: --ignore-path frontend/.prettierignore --write frontend
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Formatting changes
          branch: ${{ github.head_ref }}